<?php
/*
 * Benötige Ausgabe-Variablen
 * 
 * $ausgabe['title']   - Titel der HTML-Seite (auch h1-Tag)
 * $ausgabe['include'] - Name der einzubindenen Templatedatei
 */
?>
<!DOCTYPE html>
<html lang="de">
    <head>
        <meta charset="UTF-8">
        <title><?= $ausgabe['title'] ?? '' ?></title>
        <link href="adressen.css" rel="stylesheet">
    </head>
    <body>
        <h1><?= $ausgabe['title'] ?? '' ?></h1>
        <hr>
        <?=        
        include $ausgabe['include'];
        ?>
    </body>
</html>